# version: '3.8'

name: crypto_bot

services:
  bot:
    build: .
    container_name: crypto_bot
    env_file: .env.docker
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NATS_URL=${NATS_URL}
    volumes:
      - ./bot.py:/app/bot.py
      - ./database:/app/database
      - ./requirements.txt:/app/requirements.txt
      - ./alembic:/app/alembic
      - ./scripts:/app/scripts
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      nats:
        condition: service_started
    restart: always

  db:
    image: postgres:15
    env_file: .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: crypto_bot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:

      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-replica-1:
    image: redis:6.2
    command: redis-server --appendonly yes --replica-read-only yes --replicaof redis 6379
    depends_on:
      - redis

  redis-replica-2:
    image: redis:6.2
    command: redis-server --appendonly yes --replica-read-only yes --replicaof redis 6379
    depends_on:
      - redis

  nats:
    image: nats:latest
    command: ["-js", "-sd", "/data"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data

volumes:
  pgdata:
  redis_data: