"""add condition_type and currency_type to alerts

Revision ID: d661d7323fda
Revises: 
Create Date: 2025-02-03 19:55:52.711051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd661d7323fda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'currency', name='uix_user_currency')
    )
    op.add_column('alerts', sa.Column('user_currency_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('condition_type', sa.String(), nullable=False))
    op.add_column('alerts', sa.Column('currency_type', sa.String(), nullable=False))
    op.add_column('alerts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('last_triggered_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('alerts', 'threshold',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
    op.create_unique_constraint('uix_user_currency_alert_type', 'alerts', ['user_id', 'user_currency_id', 'condition_type', 'currency_type'], sqlite_on_conflict='IGNORE')
    op.create_foreign_key(None, 'alerts', 'user_currencies', ['user_currency_id'], ['id'], ondelete='CASCADE')
    op.drop_column('alerts', 'threshold_type')
    op.drop_column('alerts', 'currency')
    op.drop_column('alerts', 'in_rub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('in_rub', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('threshold_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint('uix_user_currency_alert_type', 'alerts', type_='unique')
    op.alter_column('alerts', 'threshold',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
    op.drop_column('alerts', 'last_triggered_at')
    op.drop_column('alerts', 'is_active')
    op.drop_column('alerts', 'currency_type')
    op.drop_column('alerts', 'condition_type')
    op.drop_column('alerts', 'user_currency_id')
    op.drop_table('user_currencies')
    # ### end Alembic commands ###
