"""Add UserCurrency table and relationships

Revision ID: 15899945bbd2
Revises: dfba55903c2b
Create Date: 2025-01-23 22:57:07.418106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15899945bbd2'
down_revision: Union[str, None] = 'dfba55903c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alerts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('last_notification', sa.TIMESTAMP(), nullable=True))
    op.add_column('crypto_rates', sa.Column('price_rub', sa.DECIMAL(precision=18, scale=8), nullable=True))
    op.add_column('crypto_rates', sa.Column('last_update', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_rates', 'last_update')
    op.drop_column('crypto_rates', 'price_rub')
    op.drop_column('alerts', 'last_notification')
    op.drop_column('alerts', 'is_active')
    op.drop_table('user_currencies')
    # ### end Alembic commands ###
