"""Update alerts table

Revision ID: 18ab11aa9ee2
Revises: 905a673a793d
Create Date: 2025-02-01 00:19:02.586944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ab11aa9ee2'
down_revision: Union[str, None] = '905a673a793d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('percent_change', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('alerts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('alerts', 'threshold',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
    op.drop_column('alerts', 'threshold_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('threshold_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('alerts', 'threshold',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
    op.drop_column('alerts', 'is_active')
    op.drop_column('alerts', 'percent_change')
    # ### end Alembic commands ###
