"""add percent_type column

Revision ID: 7b69494f4e6c
Revises: 18ab11aa9ee2
Create Date: 2025-02-01 02:28:18.004932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b69494f4e6c'
down_revision: Union[str, None] = '18ab11aa9ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('percent_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'percent_type')
    # ### end Alembic commands ###
